
export  enum  moviesTypes  {
    FETCH_REQUESTED = "FETCH_REQUESTED",
    MOVIES_DEFAULT = "MOVIES_DEFAULT",
    FETCH_FAILED = "FETCH_FAILED",

    ACTIVE_SEARCH_BY_TITLE_BUTTON_START = "ACTIVE_SEARCH_BY_TITLE_BUTTON_START",
    ACTIVE_SEARCH_BY_TITLE_BUTTON_SUCCESS = "ACTIVE_SEARCH_BY_TITLE_BUTTON_SUCCESS",
    ACTIVE_SEARCH_BY_TITLE_BUTTON_FAILE = " ACTIVE_SEARCH_BY_TITLE_BUTTON_FAILE",

    ACTIVE_SEARCH_BY_GENRE_BUTTON_START = "ACTIVE_SEARCH_BY_GENRE_BUTTON_START",
    ACTIVE_SEARCH_BY_GENRE_BUTTON_SUCCESS = "ACTIVE_SEARCH_BY_GENRE_BUTTON_SUCCESS",
    ACTIVE_SEARCH_BY_GENRE_BUTTON_FAILE = " ACTIVE_SEARCH_BY_GENRE_BUTTON_FAILE",


    GET_VALUE_FROM_FORM = "GET_VALUE_FROM_FORM"
}
