export enum  particularFilmTypes {
    FETCH_FILM_BY_ID_START = "FETCH_FILM_BY_ID_START",
    FETCH_FILM_BY_ID_SUCCESS = "FETCH_FILM_BY_ID_SUCCESS",
    FETCH_FILM_BY_ID_FAILE = "FETCH_FILM_BY_ID_FAILE",

    ON_UPDATE_MOVIE = "ON_UPDATE_MOVIE"
}