export enum MoviesActionTypes{
    ON_START_LOADING= 'ON_START_LOADING',
    ON_END_LOADING= 'ON_END_LOADING',
    ON_SORT= 'ON_SORT',
    ON_REQUEST_MOVIES= 'ON_REQUEST_MOVIES',
    ON_REQUEST_MOVIES_SUCCESS= 'ON_REQUEST_MOVIES_SUCCESS',
    ON_REQUEST_MOVIES_ERROR= 'ON_REQUEST_MOVIES_ERROR',
    ON_REQUEST_MOVIES_BY_TITLE= 'ON_REQUEST_MOVIES_BY_TITLE',
    ON_REQUEST_MOVIES_BY_TITLE_SUCCESS= 'ON_REQUEST_MOVIES_BY_TITLE_SUCCESS',
    ON_REQUEST_MOVIES_BY_TITLE_ERROR= 'ON_REQUEST_MOVIES_BY_TITLE_ERROR',
    ON_REQUEST_MOVIES_BY_GENRE= 'ON_REQUEST_MOVIES_BY_TITLE',
    ON_REQUEST_MOVIES_BY_GENRE_SUCCESS= 'ON_REQUEST_MOVIES_BY_TITLE_SUCCESS',
    ON_REQUEST_MOVIES_BY_GENRE_ERROR= 'ON_REQUEST_MOVIES_BY_TITLE_ERROR'
}

export enum MovieActionTypes{
    ON_INIT_MOVIE= 'ON_INIT_MOVIE',
    ON_UPDATE_MOVIE= 'ON_UPDATE_MOVIE'
}

