export enum MoviesActionTypes{
    ON_REQUEST_MOVIES= 'REQUEST_MOVIES',
    ON_REQUEST_MOVIES_SUCCESS= 'REQUEST_MOVIES_SUCCESS',
    ON_REQUEST_MOVIES_ERROR= 'REQUEST_MOVIES_ERROR',
}

export enum MovieActionTypes{
    ON_REQUEST_MOVIE= 'REQUEST_MOVIE',
    ON_REQUEST_MOVIE_SUCCESS= 'REQUEST_MOVIE_SUCCESS',
    ON_REQUEST_MOVIE_ERROR= 'REQUEST_MOVIE_ERROR',
}

